docker-compose.yml
docs/docker/installation.md
docs/setup.md
package.json
scripts/demo/linux.sh

* Adds scripts to build/run the containers, and update the docs with the new commands:
```
yarn docker:build:devel
yarn docker:run:devel
```
In addition to being simpler than invoking `docker-compose` directly, these commands will also `touch .env` beforehand, to ensure the `.env` file is created before docker-compose attempts to read it.
* Deletes the current `.env` file, which should hopefully go back to being gitignored locally.
* Adds the new configuration options to `docker-compose.yml` which should allow docker-compose v1.28.5+ to use the `"nvidia"` runtime without needing to set `"default-runtime": "nvidia"` in `/etc/docker/daemon.json`. Instructions on how to modify this file for older versions of docker-compose have been left in place.
Branched from …

Add docker npm scripts, update docs

---

.github/workflows/docs.yaml

This PR adds a GitHub Action for automatically updating the `gh-pages` branch with the latest docs.
It works by checking out both the `main` and `gh-pages` branches to separate directories, doing a doc build in the `main` directory, copying the results to the `gh-pages` directory, then finally committing/pushing the changes to the `gh-pages` branch.
I added the `paths` key to try to eliminate excessive builds from irrelevant file changes, but this can be tweaked/removed if necessary (file matching patterns are [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-file-paths))

Add GH action for docs

---

.github/workflows/docs.yaml

This PR fixes the GitHub Action added in #119. The screenshot below shows the `git` related error messages that occurred when the docs tried to deploy. The `git` version was older than is supported by the `actions/checkout` stage, and therefore the repo was cloned using GitHub's API instead of `git`. As a result, the doc changes could not be committed in the final stage of the pipeline. This PR updates the `node` image to an image with a newer version of `git`. It also updates the `git push` command. The correct syntax should've been `github push origin gh-pages`, but the last two parameters are optional anyway.

Fix GitHub Action for Docs

---

modules/cudf/src/column.cpp
modules/cudf/src/column.ts
modules/cudf/src/column/re.cpp
modules/cudf/src/node_cudf/column.hpp
modules/cudf/src/series/string.ts
modules/cudf/test/series/string-tests.ts

issues: closes #120 
```node
> a = Arrow.Utf8Vector.from(["foo bar baz", "baz bar foo", "foo bar foo", "baz quux"])
> s = cudf.StringSeries.new(a)
StringSeries { _col: Column {} }
> [...s.containsRe("foo").toArrow()]
[ true, true, true, false ]
> [...s.countRe("foo").toArrow()]
[ 1, 1, 2, 0 ]
> [...s.matchesRe("foo").toArrow()]
[ true, false, true, false ]
```
Still needs tests and `findall_re` (or a separate issue)

Add regex series functions

---

modules/cudf/src/node_cudf/table.hpp
modules/cudf/src/series.ts
modules/cudf/src/table.cpp
modules/cudf/src/table.ts
modules/cudf/src/table/copying.cpp
modules/cudf/test/cudf-series-test.ts

Supports scattering single scalars or other series:
```typescript
const col     = Series.new({type: new Int32, data: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]});
const indices = Series.new({type: new Int32, data: [2, 4, 5, 8]});
col.scatter(999, indices);
const values  = Series.new({type: new Int32, data: [200, 400, 500, 800]});
col.scatter(values, indices);
```
Needs a few more tests but ready for a first review. 
Edit: added `setValue`

Add scatter for Series

---

.github/workflows/docs.yaml

From looking at the docs site (https://rapidsai.github.io/node-rapids/), it seems that the docs use the repo's [README.md](https://github.com/rapidsai/node-rapids/blob/main/README.md) file for the index page.
This PR updates the GitHub Action that publishes the docs to run anytime the `README.md` file is changed.

Update github action paths

---

.yarnrc
modules/core/CMakeLists.txt
modules/core/cmake/Modules/ConfigureCUDF.cmake
modules/core/cmake/Modules/ConfigureCUSPATIAL.cmake
modules/core/cmake/Modules/ConfigureCXX.cmake
modules/core/cmake/Modules/ConfigureCuGraph.cmake
modules/core/cmake/Modules/ConfigureOpenGLEW.cmake
modules/core/cmake/Modules/ConfigureOpenGLFW.cmake
modules/core/cmake/Modules/ConfigureRAFT.cmake
modules/core/cmake/Modules/ConfigureRMM.cmake
modules/core/cmake/Modules/get_cpm.cmake
modules/cuda/CMakeLists.txt
modules/cudf/CMakeLists.txt
modules/cugraph/CMakeLists.txt
modules/cuspatial/CMakeLists.txt
modules/glfw/CMakeLists.txt
modules/rmm/CMakeLists.txt
modules/webgl/CMakeLists.txt
package.json
scripts/clean/linux.sh
scripts/exec.js
yarn.lock

This PR ensures CPM downloads and builds the RAPIDS C++ dependencies into a central location, then found and used for any downstream builds.
An example:
1. `@rapidsai/cudf` calls `CPMFindPackage(cudf)`
a. `CPMAddPackage` clones `rapidsai/cudf` repo and stores it in `modules/.cache/cpm/cudf`
b. `libcudf` sources are built as part of the `node_cudf` CMake build
* `libcudf.so` and related `.o` files are placed in `modules/.cache/build/cudf-build`
4. `@rapidsai/cugraph` calls `CPMFindPackage(cudf)`
a. `CPMFindPackage` finds `libcudf` in `modules/.cache/build/cudf-build` (built in step 1b.)
* `@rapidsai/cugraph` does not rebuild `libcudf.so` or any of its objects
5. `@rapidsai/cuspatial` calls `CPMFindPackage(cudf)`
a. `CPMFindPackage` finds `libcudf` in `modules/.cache/build/cudf-build` …

Ensure CPM dependencies build (once) in a common location

---

node-rapids.code-workspace

This PR adds a `typescript.tsdk` entry to the workspace file, which sets the default TypeScript installation that should be used by VS Code in the workspace.

Update default TypeScript Installation

---

modules/core/CMakeLists.txt
modules/core/cmake/Modules/ConfigureCuGraph.cmake
modules/cuda/CMakeLists.txt
modules/cudf/CMakeLists.txt
modules/cugraph/CMakeLists.txt
modules/cuspatial/CMakeLists.txt
modules/glfw/CMakeLists.txt
modules/rmm/CMakeLists.txt
modules/webgl/CMakeLists.txt
yarn.lock

As of 0.20 cuDF headers use C++17 features, so we need to update too.

Upgrade to C++17

---

modules/core/CMakeLists.txt
modules/core/cmake/Modules/ConfigureCUDF.cmake
modules/core/cmake/Modules/ConfigureCUSPATIAL.cmake
modules/core/cmake/Modules/ConfigureCXX.cmake
modules/core/cmake/Modules/ConfigureCuGraph.cmake
modules/core/cmake/Modules/ConfigureRMM.cmake
modules/core/cmake/Modules/get_cpm.cmake
modules/cuda/CMakeLists.txt
modules/cudf/CMakeLists.txt
modules/cugraph/CMakeLists.txt
modules/cugraph/src/layout/force_atlas2.cpp
modules/cuspatial/CMakeLists.txt
modules/glfw/CMakeLists.txt
modules/rmm/CMakeLists.txt
modules/webgl/CMakeLists.txt
node-rapids.code-workspace

* Update for `rmm::cuda_stream_view` changes
* Update CPM with a [fix for `FETCHCONTENT_BASE_DIR`](https://github.com/cpm-cmake/CPM.cmake/pull/244)
* Add shared object rpaths
* Fix typos in `glfw` and `webgl` `CMakeLists.txt`

Update CPM, fix build for latest branch-0.20 changes

---

modules/core/cmake/Modules/ConfigureCUDF.cmake
modules/core/cmake/Modules/ConfigureCUSPATIAL.cmake
modules/core/cmake/Modules/ConfigureRMM.cmake
modules/core/cmake/Modules/get_cpm.cmake
modules/cudf/src/groupby/single.ts
yarn.lock

* Fixes groupBy types causing tests/docs to not type-check
* Temporarily switch to cuDF/cuSpatial branches with the newer CPM
* Fix CMake function logic that would cause it to delete the local build dir

CPM and groupBy types followup

---

modules/core/bin/install-deps/debian.sh

This PR adds `libssl-dev` to `modules/core/bin/install-deps/debian.sh`.
Closes #124

Add libssl-dev to cmake dependencies in `debian.sh`

---

dockerfiles/devel.Dockerfile
dockerfiles/nteract.Dockerfile
package.json

Having `llnode` in our package.json entry is causing the CI docs builder to fail installing packages because it needs `lldb`. This moves llnode installation into the `devel` container's build instead.

[CI] Install llnode into the devel container, remove it from package.json

---

modules/cudf/test/cudf-column-tests.ts
modules/cudf/test/cudf-data-frame-tests.ts
modules/cudf/test/cudf-groupby-tests.ts
modules/cudf/test/cudf-series-test.ts
modules/cudf/test/dataframe/read-csv-tests.ts
modules/cudf/test/dataframe/write-csv-tests.ts

PR with a bit of cleanup in the tests. `[...ser.toArrow()]` is redundant now that we have the `Series[Symbol.iterator]()` method, because it internally calls `this.toArrow()`.

Clean up tests to use spread enumeration

---

BINDINGS.md
modules/cudf/src/series/float.ts
modules/cudf/test/cudf-series-test.ts

First basic PR to get my bearings :tada:
**Changes**
- Update `BINDINGS.md` to include `isNull` (already existing binding)
- Correct `float.ts` documentation from columns to series
- Add a `isNull` test to `cudf-series-test.ts`
**Unsure**
- `isNaN` is only available for floating point types, so I marked any instances of `isna` inside of `BINDINGS.md` to just use `isNull`.

Add series isnull binding

---

modules/cudf/src/node_cudf/utilities/cpp_to_napi.hpp
modules/cudf/src/node_cudf/utilities/scalar_to_value.hpp
modules/cudf/src/node_cudf/utilities/value_to_scalar.hpp
modules/cudf/src/scalar.cpp
modules/cudf/src/series.ts
modules/cudf/src/series/list.ts
modules/cudf/src/series/numeric.ts
modules/cudf/src/series/string.ts
modules/cudf/src/series/struct.ts
modules/cudf/src/types/dtypes.ts
modules/cudf/test/series/list-tests.ts

Now that [`cudf::get_element` supports `list_scalar`](https://github.com/rapidsai/cudf/pull/8071), we can add `ListSeries.getValue()`.
* Support creating `ListSeries` from Arrays of JS Arrays
* Move `getValue` and `setValue` to the Series subclasses to make the types happy
* Implement `ListSeries.getValue()`

[FEA] Create `ListSeries` from JS Arrays, add `ListSeries.getValue()`

---

BINDINGS.md
modules/cudf/src/column.cpp
modules/cudf/src/column.ts
modules/cudf/src/column/json.cpp
modules/cudf/src/node_cudf/column.hpp
modules/cudf/src/series/string.ts
modules/cudf/test/series/string-tests.ts

implements #179 
Example usage:
```javascript
const { Series } = require('@rapidsai/cudf');
const object_data = [{ goat: { id: 0, species: "Capra Hircus" } }, { leapord: { id: 1, species: "Panthera pardus" } }];
const a = Series.new(object_data.map(JSON.stringify));
console.log([...a.getJSONObject(`$.goat`)].map(JSON.parse)[0]); //{ id: 0, species: 'Capra Hircus' }
```

[FEA] Add `Series.getJSONObject`

---

BINDINGS.md
modules/cudf/src/data_frame.ts
modules/cudf/test/cudf-data-frame-tests.ts

Quick and easy bindings to write due to https://github.com/rapidsai/node-rapids/pull/189 and https://github.com/rapidsai/node-rapids/pull/188
**Changes**
- Added `isNotNull` to DataFrame
- Added `isNotNaN` to DataFrame
- Added `isNotNull` test to `cudf-data-frame-tests`
- Added `isNotNaN` test to `cudf-data-frame-tests`

[FEA] Added `isNotNull` and `isNotNaN`

---

docker-compose.yml
dockerfiles/devel.Dockerfile
modules/core/cmake/Modules/ConfigureCXX.cmake
node-rapids.code-workspace

* Set `CCACHE_CONFIGPATH` env var so `ccache -s` works in the container
* Set `DOCKER_WORKDIR` env var so shell history in VSCode Remote Container terminals is preserved
* Allow building the devel container with different LLDB, clangd, and clang-format versions (for testing/upgrading)
* Show the `.cmake-js` headers folder in the file explorer
* Don't launch 4 clangd processes per file
* Auto-detect VSCode workspace tasks

[FIX] docker and dev env quality

---

modules/cugraph/src/addon.ts
modules/cugraph/src/graph_coo.cpp
modules/cugraph/src/index.ts
modules/cugraph/src/node_cugraph.ts
modules/cugraph/src/node_cugraph/graph_coo.hpp
modules/demo/graph/src/loader.js

Fixes node REPL crashes reported in https://github.com/nodejs/node-addon-api/issues/1000.

[FIX] make GraphCOO `numNodes` and `numEdges` functions instead of getters

---

BINDINGS.md
modules/cudf/test/series/unaryop/float32-tests.ts
modules/cudf/test/series/unaryop/float64-tests.ts

Binding already existed, updating `BINDINGS.md` and adding tests. `DataFrame` implementation already handled.
I've marked off `StringSeries`, `ListSeries`, as having `nansToNulls` completed since this binding should be only implemented on Series of type`FloatSeries`.
**Changes**
- Added `nansToNulls` to `BINDINGS.md`
- Added Float32 & Float64 `nansToNulls` test

Added `FloatSeries` `nansToNulls`

---

BINDINGS.md
modules/cudf/src/series.ts
modules/cudf/test/cudf-series-test.ts

This previously would check `NaN` and `null`, but, I think it's reasonable just to implement this for `nulls` (as we did for `replaceNulls` for example).
https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.series.Series.count

Added `series` `countNonNulls`

---

modules/cudf/test/cudf-data-frame-tests.ts

This PR adds a missing closing bracket to the `cudf-data-frame-tests.ts` file which was preventing the docs job from running as shown in the log below.
https://github.com/rapidsai/node-rapids/runs/2634700588

Add closing bracket in `cudf-data-frame-tests.ts`

---

BINDINGS.md

This PR updates the binding table to check off `Series.unique` and `Series.value_counts`, which were done in #143.

Update Bindings Table

---

.env.sample
docker-compose.yml
docs/setup.md
modules/core/cmake/Modules/ConfigureCUGRAPH.cmake
modules/cugraph/src/layout/force_atlas2.cpp

* Use main cuGraph fork again now that https://github.com/rapidsai/cugraph/pull/1585 is merged.
* Update default `CUDA_VERSION` to 11.2.2 and `LINUX_VERSION` to ubuntu20.04.
These new defaults should work around container NCCL install path weirdness.

[FIX] Update default `CUDA_VERSION` and `LINUX_VERSION`

---

modules/core/cmake/Modules/ConfigureCUML.cmake

Now that https://github.com/rapidsai/cuml/pull/3844 is merged, we can use the rapidsai cuML fork again.

[FEA] Use rapidsai cuML fork

---

modules/core/include/nv_node/addon.hpp
modules/core/include/nv_node/objectwrap.hpp

I thought I committed these in https://github.com/rapidsai/node-rapids/pull/204, but maybe not.
* Stringify the full typeid hashcode to avoid potential hash collisions at runtime
* Move tuple `for_each` into `objectwrap.hpp`

[FIX] Clean up EnvLocalAddon and EnvLocalObjectWrap

---

BINDINGS.md
modules/cudf/src/column.cpp
modules/cudf/src/column.ts
modules/cudf/src/column/stream_compaction.cpp
modules/cudf/src/data_frame.ts
modules/cudf/src/node_cudf/column.hpp
modules/cudf/src/node_cudf/table.hpp
modules/cudf/src/node_cudf/utilities/napi_to_cpp.hpp
modules/cudf/src/series.ts
modules/cudf/src/table.cpp
modules/cudf/src/table.ts
modules/cudf/src/table/stream_compaction.cpp
modules/cudf/src/types/enums.ts
modules/cudf/src/types/mappings.ts
modules/cudf/test/cudf-data-frame-tests.ts
modules/cudf/test/cudf-series-test.ts
modules/cudf/test/dataframe/join-tests.ts
modules/demo/client-server/components/server/cudf-utils.js

This PR includes the following changes:
- Moves `drop_duplicates` method from `column` to `table` in C++
- Adds `dropDuplicates` to `Series` and `DataFrame` TS classes
- Adds unit tests for `Series.dropDuplicates` and `DataFrame.dropDuplicates`
- Updates `Series.unique` to use `Series.dropDuplicates`
- Fixes a bug that Paul noticed in `_dropNullsRows` and `_dropNansRows` where the wrong values were being pushed to the `column_indices` arrays (1a89f1e)
- Updates `NullOrder` enum values case (~~ee94e25~~ 7d68261)

Add `dropDuplicates` to `Series` and `DataFrame`

---

BINDINGS.md
modules/cudf/src/data_frame.ts
modules/cudf/src/series.ts
modules/cudf/test/cudf-data-frame-tests.ts
modules/cudf/test/cudf-series-test.ts

Using `gather` seemed like the logical choice to me.
**Changes**
- Added series `head` & `tail`
- Added dataframe `head` & `tail`
- Added tests for both

[FEA] Added bindings for `head` and `tail`

---

BINDINGS.md
modules/cudf/src/series.ts
modules/cudf/test/cudf-series-test.ts

Seemed reasonable to just take advantage of the spread operator, and use the built in `reverse()` in js.

[FEA] Added series `reverse`

---

modules/cudf/test/cudf-data-frame-tests.ts

```
Warning: You are running with an unsupported TypeScript version! TypeDoc supports 3.9, 4.0, 4.1, 4.2
Error: modules/cudf/test/cudf-data-frame-tests.ts:20:3 - error TS6133: 'Float64' is declared but its value is never read.
20   Float64,
~~~~~~~
Error: Process completed with exit code 3.
```
noticed this when github tried to build last PR.

[FIX] Remove unused declared import

---

BINDINGS.md

Was checking out the implementation for `nlargest` and saw it used the `sort_values` method internally in CUDF. Then noticed `sortValues` wasn't marked off in the `BINDINGS.md` even though it has proper implementation and tests.
https://github.com/rapidsai/node-rapids/blob/5f222ffaebe80f6fde2635316f38acfb748b7cec/modules/cudf/src/series.ts#L936

[FIX] Mark off series `sortValues` in BINDINGS.md

---

modules/cudf/src/column.cpp
modules/cudf/src/column.ts
modules/cudf/src/column/reduction.cpp
modules/cudf/src/node_cudf/column.hpp
modules/cudf/src/series.ts
modules/cudf/src/series/bool.ts
modules/cudf/src/series/float.ts
modules/cudf/src/series/integral.ts
modules/cudf/test/series/reduce/cummax-tests.ts
modules/cudf/test/series/reduce/cummin-tests.ts
modules/cudf/test/series/reduce/cumprod-tests.ts
modules/cudf/test/series/reduce/cumsum-tests.ts

This PR implements `cummax`, `cummin`, `cumprod`, and `cumsum` for `Series`
Currently `skipna=true` is finished, the `skipna=false` case is still TODO (some additional helpers need to be added)

Implement cumulative reductions for Series

---

.env.sample
docker-compose.yml
dockerfiles/devel.Dockerfile
modules/core/CMakeLists.txt
modules/core/cmake/Modules/ConfigureCUML.cmake
modules/core/cmake/Modules/ConfigureCXX.cmake
modules/core/cmake/Modules/ConfigureRMM.cmake
modules/core/cmake/Modules/ConfigureThrust.cmake
modules/core/cmake/Modules/ccache.conf.in
modules/core/cmake/Modules/thrust.patch
modules/core/src/index.ts
modules/cuda/CMakeLists.txt
modules/cudf/CMakeLists.txt
modules/cugraph/CMakeLists.txt
modules/cuml/CMakeLists.txt
modules/cuspatial/CMakeLists.txt
modules/glfw/CMakeLists.txt
modules/rmm/CMakeLists.txt
modules/webgl/CMakeLists.txt

Swaps out `ccache` for `sccache`, allowing us to share the common build cache via something like AWS S3 or GCP.

[FEA] Swap out `ccache` for `sccache`

---

.eslintrc.js
modules/core/jest.config.js
modules/core/package.json
modules/cuda/src/node_cuda/device.hpp
modules/cudf/jest.config.js
modules/cugraph/jest.config.js
modules/cuspatial/jest.config.js
modules/rmm/jest.config.js
modules/rmm/src/addon.cpp
modules/rmm/src/memory_resource.cpp
modules/rmm/src/node_rmm/memory_resource.hpp
yarn.lock

This PR:
* fixes sourcemaps when debugging VSCode tests
* fixes a typo in the jest `moduleNameMapper` regex that was missed when we renamed the modules
* fixes a (suspected) issue where the current device needs to be active when deleting an `rmm::device_memory_resource`

[FIX] Make Jest sourcemaps work again, ensure current device is active before MR destruction

---

modules/rmm/test/memory_resource/current-device-resource-tests.ts
modules/rmm/test/memory_resource/per-device-resource-tests.ts

A strict check for null was causing an undefined value to be
passed into a function that could not handle an undefined value.
------
This change is trivial and does not completely fix the tests that Paul and I were debugging. But I wanted to get a PR submitted and approved so I have the process down.

Convert strict not equals to not equals in tests

---

modules/rmm/test/memory_resource/utils.ts

cc @trxcllnt 
Spoke with Paul about this, RMM was consuming all memory and breaking the ability to run the tests on a lower spec machine.

[FIX] Reduce amount of memory RMM tests allocate

---

modules/cudf/src/dataframe/concat.ts
modules/cudf/test/dataframe/concat-tests.ts

This is how it previously used to return `never`
```ts
const result = df1.concat(df2);
// const result: DataFrame<{
//     a: never;
// }>
// IDE now autocomplete and allows calling of base level df methods
result.isNaN(); // no compiler error
```
```ts
const result = df1.concat(df2);
// const result: never
result.isNaN(); // compiler error since this entire obj is null
```

[FIX] Change df `concat` result type to `never`

---

BINDINGS.md
modules/cudf/src/data_frame.ts
modules/cudf/src/node_cudf/table.hpp
modules/cudf/src/table.cpp
modules/cudf/src/table.ts
modules/cudf/src/table/arrow.cpp
modules/cudf/test/dataframe/arrow-tests.ts

Add a static `DataFrame.fromArrow` method that can adapt Arrow tables stored in-memory in Arrow IPC format.
This is still WIP but early comments welcome. Some notes:
* As implemented, this requires a copy. Plan to to push improvements upstream to `cudf::from_arrow` to allow it to perform zero-copy when feasible (e.g. ipc buffers)
* Tests are a bit thin. Open to suggestions to improve coverage parsimoniously 
* ~~Still need to add an input type to `fromArrow` (similar to `readCSV`) so that full types can be deduced~~

Add DataFrame.fromArrow

---

modules/cudf/src/column.cpp

This fix (from @trxcllnt) resolves hard crashes that can show up sporadically in `test/series/list-tests.ts`
>what():  exclusive_scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
Using the initializer list construction could result in the column view being improperly initialized.

Fix exclusive_scan test crash

---

BINDINGS.md
modules/cudf/src/column.cpp
modules/cudf/src/column.ts
modules/cudf/src/column/copying.cpp
modules/cudf/src/node_cudf/column.hpp
modules/cudf/src/series.ts
modules/cudf/test/cudf-series-test.ts
modules/cudf/test/series/list-tests.ts
modules/cudf/test/series/string-tests.ts
modules/cudf/test/series/struct-tests.ts

Add binding for a deep copy of a Column
---------
Backed by a deep-copy constructor in cudf::column, so functionally very little to go wrong.
All cudf tests pass.

Add `Series` copy binding

---

README.md

I'm pretty sure we want it to be in the section below right? since `bsql` isnt a `RAPIDS libraries:`

Move bsql hyperlink

---

.github/workflows/main.pr.yml
dockerfiles/runtime/01-base.Dockerfile

We're compiling with gcc-9 but Ubuntu 18.04's default toolchain is gcc-7, leading to errors importing the compiled libs in the `ubuntu18.04` runtime containers. This PR updates `libstdc++6` in the runtime containers via the ubuntu-toolchain PPA.

[FIX] Update libstdc++-6 for Ubuntu18.04 runtime containers

---

modules/cudf/src/data_frame.ts
modules/cudf/test/cudf-data-frame-tests.ts

I needed this fix for my current branch which uses an empty `dataframe`. I did a search for any other `columns[0]` accessing without checking length but couldn't find any others.
Closes #259

[FIX] Empty dataframe initialization

---

modules/cudf/src/data_frame.ts
modules/cudf/src/dataframe/print.ts
modules/cudf/test/dataframe/print-tests.ts

Adds basic pretty-printing method to `DataFrame` e.g.
```
> console.log(new DataFrame({'a': a, 'b': b, 'c': c, 'd': d}).toString({maxColWidth: 70}))
a          b               d
0.0        0.0 ...        -Inf
1.0        1.1 ...         0.0
2.0        2.2 ... 0.693147181
3.0        3.3 ... 1.098612289
4.0        4.4 ... 1.386294361
5.0        5.5 ... 1.609437912
6.0 6.61234567 ... 1.791759469
```
Supports options:
* `maxColumns`
* `maxColWidth`
* `maxRows`
* `width`
Lots of corner cases and "fix one test break another" but I think this is at a good starting point.

Add pretty-printing df.toString

---

modules/core/cmake/Modules/ConfigureCUDF.cmake
modules/core/cmake/Modules/ConfigureRAFT.cmake
modules/core/cmake/Modules/get_cpm.cmake
modules/cudf/src/column/strings/contains.cpp

Fixes the build for the latest versions of RAPIDS dependencies.

[FIX] set `<pkg>_ROOT` instead of `<pkg>_DIR` to work around rapids-cmake libcudacxx issue

---

modules/cudf/src/column.cpp
modules/cudf/src/column.ts
modules/cudf/src/column/strings/replace.cpp
modules/cudf/src/node_cudf/column.hpp
modules/cudf/test/cudf-column-tests.ts

Quick stepping stone PR adds `Column.replaceSlice` that will later be used to implement categorical metadata support in CuGraph `hypergraph`

add Column.replaceSlice

---

modules/core/package.json
package.json
tsconfig.json
typedoc.js
yarn.lock

This PR updates the typedoc version to latest, simplifies top level `typedoc.js` by explicitly listing the module entry points, and removes `*test/**` from `tsconfig.json` includes.

Fix typedoc issues

---

.github/actions/build-and-publish-image/action.yml

I noticed the containers stopped showing up in https://github.com/rapidsai/node/packages and https://github.com/orgs/rapidsai/packages?repo_name=node.
[This GH doc](https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package) says adding a label should link them to the repo again.

[FEA] Add image vendor and source so the containers are linked to our GH repo

---

docker-compose.devel.yml
modules/cuda/.vscode/launch.json
modules/cudf/.vscode/launch.json
modules/cudf/src/data_frame.ts
modules/cudf/src/node_cudf/utilities/scalar_to_value.hpp
modules/cudf/src/node_cudf/utilities/value_to_scalar.hpp
modules/cudf/src/series.ts
modules/cudf/src/series/categorical.ts
modules/cudf/src/series/struct.ts
modules/cudf/src/table.ts
modules/cudf/src/types/dtypes.ts
modules/cudf/src/types/mappings.ts
modules/cudf/test/cudf-data-frame-tests.ts
modules/cuml/.vscode/launch.json
modules/cuspatial/.vscode/launch.json
modules/cuspatial/src/geometry.ts
modules/cuspatial/src/quadtree.ts
modules/deck.gl/.vscode/launch.json
modules/deck.gl/src/layers/graph.ts
modules/demo/.vscode/launch.json
modules/demo/spatial/color.js
modules/demo/spatial/util.js
modules/glfw/.vscode/launch.json
modules/io/.vscode/launch.json
modules/jsdom/.vscode/launch.json
modules/rmm/.vscode/launch.json
modules/webgl/.vscode/launch.json
node-rapids.code-workspace
yarn.lock

Small PR to add convenience functions I'm finding helpful while working through demos.
New methods:
* `Series.prototype.toString()`
* `Series.prototype.toArray()`
* `DataFrame.prototype.rename()`
Updates to existing methods:
* Make `type` and `init` optional in `Series.sequence()`
* Cast inputs to required dtypes in `Series.prototype.scatter()`
Also adds support for `cudf::struct_scalar`.

[FEA] Add more DataFrame and Series convenience functions

---

modules/cudf/src/column.cpp
modules/cudf/src/column.ts
modules/cudf/src/column/from_arrow.ts
modules/cudf/src/column/strings/combine.cpp
modules/cudf/src/data_frame.ts
modules/cudf/src/dataframe/print.ts
modules/cudf/src/index.ts
modules/cudf/src/node_cudf/column.hpp
modules/cudf/src/node_cudf/table.hpp
modules/cudf/src/scope.ts
modules/cudf/src/series.ts
modules/cudf/src/series/categorical.ts
modules/cudf/src/series/integral.ts
modules/cudf/src/series/list.ts
modules/cudf/src/series/string.ts
modules/cudf/src/series/struct.ts
modules/cudf/src/table.cpp
modules/cudf/src/table.ts
modules/cudf/src/table/copying.cpp
modules/cudf/src/table/stream_compaction.cpp
modules/cudf/src/types/mappings.ts
modules/cudf/src/utilities/dtypes.cpp
modules/cudf/test/cudf-scope-test.ts
modules/cudf/test/cudf-table-tests.ts
modules/cudf/test/series/categorical-tests.ts
modules/cugraph/src/hypergraph.ts
modules/cugraph/src/renumber.ts
modules/cuml/src/utilities/array_utils.ts
modules/cuspatial/src/quadtree.ts
modules/demo/sql/sql-cluster-server/index.js

This PR adds a `scope()` function that can be used to enclose blocks of code that will return a new `Series` or `DataFrame`. All other `Series` or `DataFrame` objects created in the scope will automatically have their `dispose` methods called after. 
cc @trxcllnt tracing this code, it seems to be behaving exactly as expected/intended: a non-disposed result is returned, and all other objects in `resources` were disposed. But now tests e.g. `renumber-test.ts` are failing. Is there some subtlety of applying this that I am missing? E.g. before there was `tmp.drop(['id'])` to suppress disposal, but that is not really an option now. Could that be significant?

Automatically disposing scope

---

modules/cudf/src/column.cpp
modules/cudf/src/data_frame.ts
modules/cudf/src/scope.ts
modules/cudf/test/cudf-column-tests.ts

Fixes a bug where buffers for a `Column` returned by `scope()` are disposed if they're shared with a `Column` that is disposed.
Example:
```typescript
import {Series, Uint64, scope} from '@rapidsai/cudf';
const u64s = scope(() => {
let i32s = Series.sequence({size: 10});
return i32s.view(new Uint64);
});
u64s.gather([0, 1]) // error! `i32s` and `u64s` share the same `.data` 
// DeviceBuffer, but `i32s` was disposed by scope()
```

[FIX] Make `scope` dispose at the `DeviceBuffer` level

---

modules/cudf/src/groupby/multiple.ts
modules/cudf/src/series.ts
modules/cudf/src/series/bool.ts
modules/cudf/src/series/float.ts
modules/cudf/src/series/integral.ts
modules/cudf/src/series/numeric.ts
modules/cudf/test/cudf-data-frame-tests.ts
modules/cudf/test/series/reduce/max-tests.ts
modules/cudf/test/series/reduce/min-tests.ts
modules/cudf/test/series/reduce/minmax-tests.ts

Small PR to fix the return types of `min()`, `max()`, and `minmax()`.

[FIX] Fix return types for different numeric reductions

---

modules/cugraph/src/graph.ts
modules/cugraph/src/index.ts
modules/cugraph/test/community/spectral-clustering-tests.ts
modules/cugraph/test/graph-tests.ts

Adds a `DedupedEdgesGraph` subclass of `Graph` that automatically removes duplicate edges. Spectral clustering algorithms that assume deduped edges are moved as well.
cc @trxcllnt once you are :+1: on the API, I'd like to flesh out the graph.ts tests more, they are currently a bit sparse in general.

Add DedupedEdgesGraph

---

modules/cudf/src/data_frame.ts

Was seeing 
> cuDF failure at: /opt/rapids/node/.cache/source/cudf/0820b596e5c87006d5cc7553042c1927fe7132e3/cpp/src/column/column_view.cpp:55: Null data pointer.
until `this` was added to `doNotDispose` in the outer call to `scope`, which I suppose makes sense given the reduction involving columns of `this`, but is also slightly annoying.

Add scope() to DataFrame.flatten

---

dev/dockerfiles/devel/main.Dockerfile

Update how `llnode` is installed due to [npm CLI changes](https://github.com/npm/cli/pull/4428/files#diff-5d468c4e7490359f170b4de0527ea12477a429e664f7946bf311f5183ac89f5d)

[FIX] `npm pack` then `npm install llnode` due to npm changes

---

dev/dockerfiles/devel/main.Dockerfile
dev/dockerfiles/devel/notebook.Dockerfile
dev/dockerfiles/runtime/notebook.Dockerfile

The latest release of `jupyterlab-desktop` seems to fail with the following unskippable dialog: 
Pinning to `v3.3.2` seems to work, even though it now just shows this dialog on startup: 
Doesn't seem like there's a way to configure it to not check for updates on startup, so this'll have to be good enough for now.

[FIX] Pin `jupyterlab-desktop` version

---

dev/dockerfiles/devel/main.Dockerfile
dev/dockerfiles/runtime/base.Dockerfile

Fix container builds in light of [the recent apt key rotation](https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772).

[FIX] add latest CUDA apt key

---

modules/demo/api-server/index.js
modules/demo/api-server/routes/graphology/index.js
modules/demo/api-server/test/fixtures.js
modules/demo/api-server/test/routes/graphology.test.js
modules/demo/api-server/test/routes/root.test.js
modules/demo/api-server/util/gpu_cache.js
modules/demo/api-server/util/schema.js

Previously, the index value referred to by a graphology graph `edges` list in the `source` and `target` values was being used to lookup `nodes` according to their position in the `nodes` array. This is incorrect.
This bugfix creates the `key=>index` mapping so that `source` and `target` refer to nodes by their `key` entry, not their list position.
This bugfix also moves the default `index.js` execution of `@rapidsai/demo-api-server` to port `3010`, compatible with the [sigma.js demo](https://www.github.com/jacomyal/sigma.js/pull/1252).
Finally this bugfix adds `.setNullMask` after the `getJSONObject` calls, as spurious entries in the nullmask are occurring there since the original merge https://github.com/rapidsai/node/pull/392

Fix target/source keymapping

---

modules/cuda/src/buffer.ts
modules/cuda/src/memory.ts
modules/cuda/src/memory/memory.cpp
modules/cuda/src/node_cuda/utilities/cpp_to_napi.hpp

Allow creating cuda IPC handles for all Memory types except `PinnedMemory` and `ManagedMemory`.

[FEA] allow creating cuda IPC handles for more `Memory` types

---

modules/cuspatial/src/addon.cpp
modules/cuspatial/src/addon.ts
modules/cuspatial/src/geometry.cpp
modules/cuspatial/src/index.ts
modules/cuspatial/src/node_cuspatial.ts
modules/cuspatial/src/node_cuspatial/geometry.hpp
modules/cuspatial/src/spatial.ts
modules/cuspatial/test/quadtree-tests.ts
modules/cuspatial/test/spatial-tests.ts

This PR makes the lon_lat_to_cartesian function in cuspatial available in `node-rapids`, including one basic test.
Closes #441

Link createLonLatToCartesian in `@rapidsai/cuspatial`

---

.github/workflows/build-and-push-image-ssh.yml
.github/workflows/build-and-push-image.yml
.github/workflows/main.pr.yml
.github/workflows/release.yml

This PR is updating the runner labels to use ARC V2 self-hosted runners for CPU jobs only. This is needed to resolve the auto-scalling issues.

Use ARC V2 self-hosted runners for CPU jobs

---

.dockerignore
.github/workflows/build-and-push-image-ssh.yml
.github/workflows/build-and-push-image.yml
.github/workflows/main.pr.yml
modules/demo/deck/arc/index.js
modules/demo/spatial/data.js
modules/demo/spatial/util.js
modules/glfw/src/callbacks.cpp
modules/glfw/src/glfw.ts
modules/jsdom/.vscode/launch.json
modules/jsdom/src/index.ts
modules/jsdom/src/polyfills/events/dnd.ts
modules/jsdom/src/polyfills/events/event.ts
modules/jsdom/src/polyfills/events/keyboard.ts
modules/jsdom/src/polyfills/events/mouse.ts
modules/jsdom/src/polyfills/events/wheel.ts
modules/jsdom/src/polyfills/events/window.ts
modules/jsdom/src/polyfills/jsdom.ts
modules/jsdom/src/polyfills/modules/import.ts
modules/jsdom/src/polyfills/modules/require.ts
modules/jsdom/test/require-tests-transpiled.ts
modules/jsdom/test/require-tests.ts
modules/jsdom/test/test-import.js
modules/jsdom/test/utils.ts
yarn.lock

* Update `tj-actions/changed-files` version
* Ensure git-lfs files are added to npm packages
* Fix segfault in `@rapidsai/jsdom` module on shutdown
* Fix issue where the `exports` object didn't behave identically b/w CJS and ESM
* Update `@rapidsai/jsdom` vm types, add additional test covering transpiled babel

[FIX] Fix demo packaging
