rapidsai/node

- modules/cudf/src/data_frame.ts
- modules/cudf/src/series.ts
```js
const values = df
.groupBy({by: 'zip'}).sum()
.sortValues({ index: { ascending: true } });
console.log([...values.toArrow().slice(0, 5)]);
```
Branched from https://github.com/rapidsai/node-rapids/pull/116.
> Add DataFrame.toArrow and DataFrame.sortValues

- modules/cudf/src/column.cpp
- modules/cudf/src/column.ts
- modules/cudf/src/column/filling.cpp
- modules/cudf/src/node_cudf/column.hpp
- modules/cudf/src/series.ts
- modules/cudf/src/series/numeric.ts
- modules/cudf/test/cudf-series-test.ts
Very basic tests. Happy to make follow-on issue for more tests after GTC
> add static Series.sequence method

- .gitignore
- modules/cudf/notebooks/Basic Demo.ipynb
cc @trxcllnt @exactlyallan 
Data file is located here:
https://www.kaggle.com/sobhanmoosavi/us-accidents?select=US_Accidents_Dec20.csv
and should be saved under `modules/cudf/notebooks/data`.
Open `nteract` docker by running:
```sh
yarn docker:run:nteract
```
Open the notebook `modules/cudf/notebooks/Basic Demo.ipynb` (make sure to use *JavaScript (node.js)* execution kernel)
> Add Basic Cudf Demo notebook

- modules/cudf/src/column_accessor.ts
- modules/cudf/src/data_frame.ts
- modules/cudf/test/cudf-data-frame-tests.ts
> [FEA] update DataFrame.assign

- modules/core/src/index.ts
- modules/cudf/src/data_frame.ts
- modules/cudf/src/groupby.cpp
- modules/cudf/src/groupby/single.ts
> Update groupBy generic types

- modules/cudf/src/series.ts
- modules/cudf/test/cudf-series-test.ts
follow-up PR to #151, added support bool8 type inference and tests
> add bool8 type inference

- modules/cudf/src/series.ts
- modules/cudf/test/cudf-series-test.ts
- modules/demo/spatial/app.js
remove inplace operation for scatter & setValue, and return Series<T> instead
> [Fix] remove scatter & setValue inplace

- modules/cudf/src/column_accessor.ts
- modules/cudf/src/data_frame.ts
- modules/cudf/src/dataframe/join.ts
- modules/cudf/src/node_cudf/table.hpp
- modules/cudf/src/table.cpp
- modules/cudf/src/table.ts
- modules/cudf/src/table/copying.cpp
- modules/cudf/src/table/join.cpp
- modules/cudf/test/dataframe/join-tests.ts
This is still WIP. Wandered down some wrong paths, but I think it is the right general approach.
There is currently some issue with right joins, but other wise this is ready for a look.
> Add Support for joins

- modules/cudf/src/column/stream_compaction.cpp
- modules/deck.gl/src/buffer.ts
- modules/demo/ipc/umap/app.js
- modules/demo/ipc/umap/index.js
- modules/demo/ipc/umap/layers/arrow-graph-layer.js
- modules/demo/ipc/umap/layers/edge/bezier-curve-layer-fragment.glsl.js
- modules/demo/ipc/umap/layers/edge/bezier-curve-layer-vertex.glsl.js
- modules/demo/ipc/umap/layers/edge/bezier-curve-layer.js
- modules/demo/ipc/umap/layers/edge/edge-positions-vertex.glsl.js
- modules/demo/ipc/umap/layers/node/node-layer-fragment.glsl.js
- modules/demo/ipc/umap/layers/node/node-layer-vertex.glsl.js
- modules/demo/ipc/umap/layers/node/node-layer.js
- modules/demo/ipc/umap/layers/utils.js
- modules/demo/spatial/app.js
- modules/demo/spatial/color.js
- modules/demo/spatial/index.js
- modules/glfw/src/addon.cpp
- modules/glfw/src/addon.hpp
- modules/glfw/src/callbacks.cpp
- modules/glfw/src/cursor.cpp
- modules/glfw/src/errors.hpp
- modules/glfw/src/events.cpp
- modules/glfw/src/joystick.cpp
- modules/glfw/src/monitor.cpp
- modules/glfw/src/vulkan.cpp
- modules/glfw/src/window.cpp
- modules/glfw/test/cuda-gl-interop-tests.js
- yarn.lock
See https://github.com/rapidsai/node-rapids/pull/171 for more info.
* Update `@nvidia/glfw`, `@rapidsai/deck.gl`, and demo modules for the API changes in the previous 8 PRs
* Light cleanup
> [9/9] Update glfw, deck.gl, and demos for latest EnvLocal API changes

- modules/cudf/src/data_frame.ts
- modules/cudf/src/dataframe/join.ts
- modules/cudf/test/dataframe/join-tests.ts
> Find common types for joins

- BINDINGS.md
- modules/cudf/src/data_frame.ts
- modules/cudf/test/cudf-data-frame-tests.ts
**Changes**
- Adds trig, inverse, and hyperbolic functions to `dataframe`
**Unknown**
- Do we want to pass in a `memoryResource` to all these?
> [FEA] `DataFrame` Math Ops: Trig, Inverse, and Hyperbolic

- BINDINGS.md
- modules/cudf/src/data_frame.ts
- modules/cudf/test/cudf-data-frame-tests.ts
**Changes**
- Added exp, log, sqrt, cbrt, ceil, floor, abs, not to `dataframe`
- Added respective tests as well for each of these.
> Added more `dataframe` unaryops

- modules/core/include/nv_node/utilities/span.hpp
- modules/cudf/src/column.cpp
- modules/cudf/src/node_cudf/scalar.hpp
- modules/cudf/src/scalar.cpp
- modules/cuspatial/test/quadtree-tests.ts
- modules/rmm/src/device_buffer.cpp
- modules/rmm/src/node_rmm/device_buffer.hpp
A PR of a few random small clean up things that don't really align with larger features.
> Clean up EnvLocalAddon, Span, DeviceBuffer, Column, Scalar

- BINDINGS.md
- modules/cudf/src/data_frame.ts
- modules/cudf/test/cudf-data-frame-tests.ts
- modules/cudf/test/cudf-series-test.ts
`cast` already exists, write tests and update the bindings doc.
> Series/DataFrame `astype` `cast`

- BINDINGS.md
- modules/core/cmake/Modules/ConfigureCUML.cmake
- modules/core/package.json
- modules/cuda/src/buffer.ts
- modules/cuda/src/device.ts
- modules/cudf/src/column_accessor.ts
- modules/cudf/src/data_frame.ts
- modules/cudf/src/dataframe/concat.ts
- modules/cudf/src/dataframe/join.ts
- modules/cudf/src/node_cudf/table.hpp
- modules/cudf/src/table.cpp
- modules/cudf/src/table.ts
- modules/cudf/src/table/concatenate.cpp
- modules/cudf/src/types/mappings.ts
- modules/cudf/src/utilities/dtypes.cpp
- modules/cudf/test/cudf-data-frame-tests.ts
- modules/cudf/test/dataframe/join-tests.ts
- modules/cudf/test/series/binaryop/int16-tests.ts
- modules/cudf/test/series/binaryop/int32-tests.ts
- modules/cudf/test/series/binaryop/int64-tests.ts
- modules/cudf/test/series/binaryop/int8-tests.ts
- modules/cudf/test/series/binaryop/uint16-tests.ts
- modules/cudf/test/series/binaryop/uint32-tests.ts
- modules/cudf/test/series/binaryop/uint64-tests.ts
- modules/cudf/test/series/binaryop/uint8-tests.ts
- modules/cudf/test/series/utils.ts
- modules/webgl/src/webgl.ts
- package.json
- yarn.lock
Closes https://github.com/rapidsai/node-rapids/issues/97
> [FEA] Dataframe `concat`

- modules/cudf/src/data_frame.ts
Just some minor doc string changes I noticed while working on a different PR.
> Fix errors in `dataframe` docstrings

- modules/cudf/src/column.cpp
- modules/cudf/src/column.ts
- modules/cudf/src/column/transform.cpp
- modules/cudf/src/node_cudf/column.hpp
- modules/cudf/src/node_cudf/utilities/buffer.hpp
- modules/cudf/src/series.ts
- modules/cudf/src/utilities/buffer.cpp
- modules/cudf/test/cudf-column-tests.ts
- modules/rmm/src/device_buffer.cpp
- modules/rmm/src/node_rmm/device_buffer.hpp
PR to make `setNullMask()` work as expected.
> [BUG] Fix `Column.setNullMask`, add tests, move Column buffer helpers to utilities

- BINDINGS.md
- modules/cudf/src/series/numeric.ts
- modules/cudf/test/series/reduce/kurtosis-tests.ts
- modules/cudf/test/series/reduce/skew-tests.ts
Quick PR to add `Series.skew` and `Series.kurtosis`.
> Add Series.skew and Series.kurtosis

- BINDINGS.md
- modules/cudf/src/data_frame.ts
- modules/cudf/test/cudf-data-frame-tests.ts
**Changes**
- Added dataframe `replaceNulls`
- Added dataframe `replaceNulls` test
> [FEA] Added dataframe-replaceNulls

- BINDINGS.md
- modules/cudf/src/series.ts
- modules/cudf/test/cudf-series-test.ts
https://github.com/rapidsai/cudf/blob/90fe10b2947c9caee998f6236d432f3742c3504e/python/cudf/cudf/core/series.py#L3242
> [FEA] Add `nlargest`, `nsmallest` series binding

- BINDINGS.md
These operations don't work on Lists, strings, structs. Should be able to just mark them off.
> Mark off skew, kurtosis, in bindings

- BINDINGS.md
- modules/cudf/src/data_frame.ts
- modules/cudf/test/cudf-data-frame-tests.ts
From my testing, this should always return `never` if provided an invalid DataFrame containing non numeric Series.
> [FEA] `Kurtosis` and `skew` for dataframe

- modules/cudf/src/data_frame.ts
- modules/cudf/src/series/bool.ts
- modules/cudf/src/series/float.ts
- modules/cudf/src/series/integral.ts
- modules/cudf/src/series/numeric.ts
- modules/cudf/test/series/reduce/all-tests.ts
- modules/cudf/test/series/reduce/any-tests.ts
- modules/cudf/test/series/reduce/cummax-tests.ts
- modules/cudf/test/series/reduce/cummin-tests.ts
- modules/cudf/test/series/reduce/cumprod-tests.ts
- modules/cudf/test/series/reduce/cumsum-tests.ts
- modules/cudf/test/series/reduce/kurtosis-tests.ts
- modules/cudf/test/series/reduce/mean-tests.ts
- modules/cudf/test/series/reduce/median-tests.ts
- modules/cudf/test/series/reduce/product-tests.ts
- modules/cudf/test/series/reduce/skew-tests.ts
- modules/cudf/test/series/reduce/std-tests.ts
- modules/cudf/test/series/reduce/sum-tests.ts
- modules/cudf/test/series/reduce/sumOfSqaures-tests.ts
- modules/cudf/test/series/reduce/variance-tests.ts
Renamed for clarity, no functional change
Resolves: #231
-----
Builds and passes MOST tests. There is an issue with the rmm tests on a few machines, but the change introduces no additional failures, so I consider it well enough tested. If anyone with working tests wants to verify it passes all tests be my guest, but there should be zero functionality change, this was just a ctrl+r change.
> Rename skipna to skipNulls

- modules/cudf/test/cudf-column-tests.ts
---------
Fixes a failing test on only lower memory devices by limiting the amount of memory tests allocate
change written by @bryevdv
> Fix memory allocation bug in cudf column tests

- modules/cudf/src/data_frame.ts
- modules/cudf/src/types/dtypes.ts
Closes https://github.com/rapidsai/node-rapids/issues/254
> [FEA] Move array types to dtypes

- modules/glfw/src/jsdom/index.ts
- modules/glfw/src/jsdom/keys.ts
New version of @types/node brings new compile errors
> [FIX] Fix GLFW TS compile errors

- modules/cudf/src/data_frame.ts
- modules/cudf/src/table.ts
- modules/cudf/src/table/arrow.cpp
> Follow-on for #267

- modules/cudf/src/series.ts
- modules/cudf/test/cudf-series-test.ts
> Create Series constructor for Array and Buffers

- modules/blazingsql/src/blazingcontext.ts
- modules/blazingsql/test/blazing-context-tests.ts
- yarn.lock
- Adds some more bsql tests
- Fixes queries with multiple data frames
- Adds basic documentation to current methods implemented
> Fea: Add basic bsql testing, add basic docs, fix up multi table queries

- modules/cudf/src/column.cpp
- modules/cudf/src/column.ts
- modules/cudf/src/column/convert.cpp
- modules/cudf/src/node_cudf/column.hpp
- modules/cudf/src/series.ts
- modules/cudf/src/series/bool.ts
- modules/cudf/src/series/categorical.ts
- modules/cudf/src/series/float.ts
- modules/cudf/src/series/integral.ts
- modules/cudf/src/series/list.ts
- modules/cudf/src/series/numeric.ts
- modules/cudf/src/series/string.ts
- modules/cudf/src/series/struct.ts
- modules/cudf/src/series/timestamp.ts
- modules/cudf/src/utilities/dtypes.cpp
- modules/cudf/test/cudf-column-tests.ts
- modules/cudf/test/series/string-tests.ts
- modules/cudf/test/series/timestamp-tests.ts
- modules/cudf/test/series/unaryop/float32-tests.ts
- modules/cudf/test/series/unaryop/float64-tests.ts
- modules/cudf/test/series/unaryop/int16-tests.ts
- modules/cudf/test/series/unaryop/int32-tests.ts
- modules/cudf/test/series/unaryop/int64-tests.ts
- modules/cudf/test/series/unaryop/int8-tests.ts
- modules/cudf/test/series/unaryop/uint16-tests.ts
- modules/cudf/test/series/unaryop/uint32-tests.ts
- modules/cudf/test/series/unaryop/uint64-tests.ts
- modules/cudf/test/series/unaryop/uint8-tests.ts
closes #262 
Still needs a little work:
as well as any other casts that I have missed that come up in review
> Refactor cast to use Visitor pattern

- modules/blazingsql/README.md
Direct link https://github.com/rapidsai/node-rapids/blob/375c0dca60735f5a81098031f000539d3f83498f/modules/blazingsql/README.md
> Add doc link to BlazingSQL readme

- .github/workflows/main.merge.yml
- .github/workflows/main.pr.yml
- modules/core/bin/cmake-js/linux.sh
- modules/core/cmake/Modules/ConfigureCUDF.cmake
- package.json
- scripts/exec.js
Testing whether the PR builder properly reports failures when building the packages in the devel-main container.
> [FIX] Ensure PR builder reports errors

- modules/sql/README.md
Just old API I noticed when writing my blog
> Fix SQL readme doc

- modules/demo/sql/sql-cluster-server/index.js
From what it seems like it doesn't climb anymore, I tested on a 2.6gb file.
> Free memory usage in SQL demo

- .dockerignore
- .gitattributes
- .github/actions/build-and-publish-image-ssh/action.yml
- .github/workflows/main.pr.yml
- .github/workflows/merge.pr.yml
- .github/workflows/release.yml
- .gitignore
- dev/dockerfiles/devel/package.Dockerfile
* switch to self-hosted runners
* use the new SSH keys
* mount ssh-agent action files into packages image build
> [FEA] switch to self-hosted runners (#407)

- modules/cudf/src/column.ts
- modules/cudf/src/column/json.cpp
- modules/cudf/src/data_frame.ts
- modules/cudf/src/dataframe/join.ts
- modules/cudf/src/node_cudf/column.hpp
- modules/cudf/src/node_cudf/utilities/napi_to_cpp.hpp
- modules/cudf/src/series.ts
- modules/cudf/src/series/string.ts
- modules/cudf/src/types/enums.ts
- modules/cudf/src/types/json.ts
- modules/cudf/test/dataframe/write-read-parquet-tests.ts
- modules/cudf/test/series/string-tests.ts
> [FIX] Fix orc/parquet type deserialization

- modules/core/cmake/Modules/ConfigureArrow.cmake
- modules/core/cmake/Modules/ConfigureBlazingSQL.cmake
- modules/core/cmake/Modules/ConfigureCUDF.cmake
- modules/core/cmake/Modules/ConfigureCUGRAPH.cmake
- modules/core/cmake/Modules/ConfigureCUGRAPHOPS.cmake
- modules/core/cmake/Modules/ConfigureCUML.cmake
- modules/core/cmake/Modules/ConfigureCUMLPRIMS.cmake
- modules/core/cmake/Modules/ConfigureCUSPATIAL.cmake
- modules/core/cmake/Modules/ConfigureCXX.cmake
- modules/core/cmake/Modules/ConfigureRAFT.cmake
- modules/core/cmake/Modules/ConfigureRMM.cmake
- modules/core/cmake/Modules/get_cpm.cmake
- modules/core/cmake/Modules/get_nccl.cmake
- modules/cudf/src/column.cpp
- modules/cudf/src/data_frame.ts
- modules/cudf/test/cudf-series-test.ts
- modules/cudf/test/series/string-tests.ts
- yarn.lock
Fix a missing symbol error in the `v22.12.0` packages, fix failing tests, general CMake cleanup.
> Fix `arrow::cuda` static link error
